
version: 0.1

phases:
  install:
    commands:
      - ls
      - cd ./personal-site-ui
      - ls
      - npm install
      - cd ../personal-site-server
      - ls
      - npm install
  build:
    commands:
      - cd ./personal-site-ui
      - npm run build
