
version: 0.2

phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - npm --prefix ./personal-site-model install ./personal-site-model
      - npm --prefix ./personal-site-shapes install ./personal-site-shapes
      - npm --prefix ./personal-site-content install ./personal-site-content
      - npm --prefix ./personal-site-server install ./personal-site-server
      - npm --prefix ./personal-site-ui install ./personal-site-ui
    pre_build:
      commands:
        - echo Logging in to Amazon ECR...
        - aws --version
        - $(aws ecr get-login --region us-east-1 --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR/personal-site-ui
      - npm run build
      - cd $CODEBUILD_SRC_DIR
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  post_build:
    commands:
      - printf '[{"name":"personal-site-container","imageUri":"%s"}]' $REPOSITORY_URI:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7) > imagedefinitions.json
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - eval $(aws ecr get-login --no-include-email | sed 's|https://||')
      - docker push $REPOSITORY_URI:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

artifacts:
  files:
    - '**/*'
