
version: 0.1

phases:
  install:
    commands:
      - ls
      - cd $CODEBUILD_SRC_DIR/personal-site-ui
      - ls
      - npm install
      - cd $CODEBUILD_SRC_DIR/personal-site-server
      - ls
      - npm install
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/personal-site-ui
      - npm run build
