
version: 0.2

phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR/personal-site-ui
      - npm install
      - cd $CODEBUILD_SRC_DIR/personal-site-server
      - npm install
      - cd $CODEBUILD_SRC_DIR/personal-site-model
      - npm install
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/personal-site-ui
      - npm run build
