
version: 0.1

phases:
  install:
    commands:
      - ls
      - echo $CODEBUILD_SRC_DIR_personal-site
      - cd $CODEBUILD_SRC_DIR_personal-site/personal-site-ui
      - npm install
      - cd $CODEBUILD_SRC_DIR_personal-site/personal-site-server
      - npm install
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR_personal-site/personal-site-ui
      - npm run build
