
version: 0.2

phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR/personal-site-model
      - npm install
      - cd $CODEBUILD_SRC_DIR/personal-site-ui
      - npm install
      - cd $CODEBUILD_SRC_DIR/personal-site-server
      - npm install
    pre_build:
      commands:
        - echo Logging in to Amazon ECR...
        - aws --version
        - $(aws ecr get-login --region us-east-1 --no-include-email)
        - REPOSITORY_URI=276223127361.dkr.ecr.us-east-1.amazonaws.com/carroll/shane
        - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/personal-site-ui
      - npm run build
      - cd $CODEBUILD_SRC_DIR
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 276223127361.dkr.ecr.us-east-1.amazonaws.com/carroll/shane:latest .
      - docker tag 276223127361.dkr.ecr.us-east-1.amazonaws.com/carroll/shane:latest 276223127361.dkr.ecr.us-east-1.amazonaws.com/carroll/shane:$IMAGE_TAG
  post_build:
    commands:
      - printf '[{"name":"hello-world","imageUri":"%s"}]' 276223127361.dkr.ecr.us-east-1.amazonaws.com/carroll/shane:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - '**/*'
