
version: 0.2

phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR/personal-site-model
      - npm install
      - cd $CODEBUILD_SRC_DIR/personal-site-ui
      - npm install
      - cd $CODEBUILD_SRC_DIR/personal-site-server
      - npm install
    pre_build:
      commands:
        - echo Logging in to Amazon ECR...
        - aws --version
        - $(aws ecr get-login --region us-east-1 --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR/personal-site-ui
      - npm run build
      - cd $CODEBUILD_SRC_DIR
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  post_build:
    commands:
      - printf '[{"name":"personal-site-container","imageUri":"%s"}]' $REPOSITORY_URI:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7) > imagedefinitions.json
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
